netwitness:
        settings:
                host: '172.30.254.200'
                port: '50103'
                path: 'sdk'
                ssl: 'enabled'
        auth:
                user: 'admin'
                pass: 'netwitness'